### ISSUE TITLE
Support for AGP 8

### ISSUE THREAD

**Issue by sneglia9191** [blaugold/iabtcf_consent_info#18]
Getting this issue when building after upgrading to AGP 8+:

Incorrect package="com.gabriel.terwesten.iabtcf_consent_info" found in source AndroidManifest.xml: /Users/sneglia/.pub-cache/hosted/pub.dev/iabtcf_consent_info-3.1.0/android/src/main/AndroidManifest.xml.
Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported.
Recommendation: remove package="com.gabriel.terwesten.iabtcf_consent_info" from the source AndroidManifest.xml: /Users/sneglia/.pub-cache/hosted/pub.dev/iabtcf_consent_info-3.1.0/android/src/main/AndroidManifest.xml.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':iabtcf_consent_info:processDebugManifest'.
> A failure occurred while executing com.android.build.gradle.tasks.ProcessLibraryManifest$ProcessLibWorkAction
   > Incorrect package="com.gabriel.terwesten.iabtcf_consent_info" found in source AndroidManifest.xml: /Users/sneglia/.pub-cache/hosted/pub.dev/iabtcf_consent_info-3.1.0/android/src/main/AndroidManifest.xml.
     Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported.
     Recommendation: remove package="com.gabriel.terwesten.iabtcf_consent_info" from the source AndroidManifest.xml: /Users/sneglia/.pub-cache/hosted/pub.dev/iabtcf_consent_info-3.1.0/android/src/main/AndroidManifest.xml.

**Comment by storeIt** [comment]
You could fix this issue with deletion of the package line in AndroidManifest. Delete this: 'package="com.gabriel.terwesten.iabtcf_consent_info' and you will have an empty manifest tag like: '<manifest></manifest>
'.

**Comment by osmanozturk** [comment]
Doing that is not enough, it still complains about the namespace even if you add the main gradle fix and kotlin version. Library needs an update for AGP 8

**Comment by large** [comment]
It does not only concern this package, but here is a hack to handle all packages that has not yet upgraded to AGP 8.x, add this to the allprojects part in your build.gradle (android):
```gradle
allprojects {
    afterEvaluate { project ->
        if (project.hasProperty('android')) {
            project.android {
                if (namespace == null) {
                    namespace project.group
                }
            }
        }
    }
}
```

**Comment by osmanozturk** [comment]
> It does not only concern this package, but here is a hack to handle all packages that has not yet upgraded to AGP 8.x, add this to the allprojects part in your build.gradle (android):
> ```gradle
> allprojects {
>     afterEvaluate { project ->
>         if (project.hasProperty('android')) {
>             project.android {
>                 if (namespace == null) {
>                     namespace project.group
>                 }
>             }
>         }
>     }
> }
> ```
> 
> This project should though be upgraded so it is compilled with Java 17 and not 1.8 which current version is setup todo.

That's what I meant by gradle fix but that didn't work out for me either. I will recheck the Java 17 part

**Comment by egonbeermat** [comment]
This is an incredibly useful package, but as the Flutter package ecosystem is gradually upgrading AGP, this package is in danger of gating that, by becoming stale. The above allprojects addition wasn't enough for me to move forward. It would be great if the author could resolve themselves / review the proposed PR for this fix, and move forward! Keep up the good work!

**Comment by osmanozturk** [comment]
I second that

> This is an incredibly useful package, but as the Flutter package ecosystem is gradually upgrading AGP, this package is in danger of gating that, by becoming stale. The above allprojects addition wasn't enough for me to move forward. It would be great if the author could resolve themselves / review the proposed PR for this fix, and move forward! Keep up the good work!

**Comment by egonbeermat** [comment]
Yay, thanks for updating! I was using this package in a newer project, and it wouldn't build due to a class conflict between compiled classes in my app vs the package, due to differing AGP version. Much appreciated!

**Comment by sneglia9191** [comment]
After upgrading my project to AGP 8, I get the following error on build:  

Execution failed for task ':iabtcf_consent_info:compileDebugKotlin'.
> Inconsistent JVM-target compatibility detected for tasks 'compileDebugJavaWithJavac' (1.8) and 'compileDebugKotlin' (17).

Anyone else getting this?

**Comment by blaugold** [comment]
@sneglia9191 I've updated the version of kotlin used by the plugin to the latest version. Maybe that helps. It's in version `3.3.0`.

**Comment by sneglia9191** [comment]
@blaugold, thanks for the update.  Unfortunately, it did not work.  i was able to determine a workaround.  In android/build.gradle, I added the following lines of code: 

```
allprojects { project ->

    if (project.name == "iabtcf_consent_info") { 
        tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
            kotlinOptions {
                jvmTarget = "1.8" // Or your desired JVM target
            }
        }
    }
}

```

Although, I am not an expert in Gradle, as I understand it this code is used to address a compatibility issue where the iabtcf_consent_info project, or a dependency it relies on, is not fully compatible with a newer Java version (e.g., Java 17). By specifically targeting this project and setting the jvmTarget to "1.8", it ensures that the code is compiled in a way that is compatible with the older Java version.

I only need to add. this code for two packages: iabtcf_consent_info and fluttertoast, and I only need to add it when upgrading to AGP 8.   

Hope this helps.  Thanks!

**Comment by blaugold** [comment]
Ah, interesting. I could also add the `jvmTarget` in the Plugin itself. It might help others as well.

**Comment by sneglia9191** [comment]
Success!! Thank you for making all the changes required!
